### ISSUE TITLE
Don't rely on engines.node to determine node environment

### ISSUE THREAD

**Issue by pol-ba** [bluealba/workflows-public#1]
Don't rely on engines.node to determine the node environment.
This node is used to constraint the node versions supported and it's optional. Also, this could be an expression like this: 
`"engines": {
  "node": "8.x|10.x"
}` 

https://github.com/bluealba/workflows-public/blob/f5f4257e0f0f06e8705707c5646d6747b9551c50/.github/workflows/public-package-build-test-release-yarn.yml#L18

**Comment by AlexisDaciuk** [comment]
Changed behavior in [8f359b](https://github.com/bluealba/workflows-public/commit/7122df734523d5480d310d36a31e0345a78f359b), now we use a file `.build-node-version` instead of defining it in the package.json
